### ISSUE TITLE
Magazine-server에 대한 피드백 부탁드립니다.

### ISSUE THREAD

**Issue by WON-JIN-LEE** [Hanghae99-Magazine/wonjin-server#4]
부족한 점이 너무 많지만, 아낌없는 피드백 부탁드립니다.  시간 내주셔서 감사합니다.

1. 코드 리뷰
    - 전체적인 코드 구성과 코드 스타일에서 고쳐야 하는 것과 보완되었으면 하는 부분에 대한 피드백을 받고 싶습니다.

2. 테스트 코드 피드백
    - 코드를 먼저 구현하고 나서 테스트 코드를 작성하다 보니 통합 테스트를 위주로 작성한 것 같습니다. 어떻게 접근해야 TDD 프로세스를 잘 이해하면서 개발할 수 있는지 피드백 받고 싶습니다.

**Comment by cleverleee** [comment]
안녕하세요 이번에 코멘트를 달게된 이총명이라고 합니다 :) 😊

1) 
솔직히 코드를 방어적으로 너무 잘 짜셨고요. 에러처리도 깔끔하게 해 주었습니다. 그리고 데이터 베이스 설계도 너무 잘해주셨구요.  
너무 잘하셔서 코드에 있어서 크게 흠은 없지만, 제가 조금은 아쉬웠던 점은 response 로 내려줄때 어떤 키값은 Camelcase, 어떤 키값은  스네이크 케이스(_) 를 사용해서 통일되지 않은 부분이 있었습니다. 다음에는 통일성있게 맞춰주면 훨씬 깔끔해질것 같습니다! 

2) 
통합 테스트에 대한 시나리오가 잘 짜져있습니다. 하지만 유닛 테스트에 대한 고민이 많으실겁니다. 배보다 배꼽이 큰 경우가 생길수도 있으니깐요. 하지만 실무에서 어떤 부분에 비중을 두고 하는지는 개발자 마다 다르기 때문에 현재 단계에서는 필요한 함수만 유닛 테스트로 해보면서 습관해 해보는게 더 중요한것 같습니다. 
제가 본 구글 공식문서에서는 각 테스트의 비율은 단위 테스트 70%, 통합 테스트 20%, UI 테스트 10%로 구성하는 것이 좋다고 합니다. 그렇기 때문에 작은 단위에서 부터 다음에는 해보시면 좋을것 같다는 의견입니다. 

저의 코멘트는 여기까지입니다. 코로나 조심하시고 좋은 주말 보내세요!

**Comment by WON-JIN-LEE** [comment]
이총명 튜터님 코멘트 남겨주셔서 감사합니다. 

피드백 주신부분을 잘 숙지해서 코드에 잘 적용할 수 있게 하겠습니다.
